fix: Define assinatura padrão para a aplicação

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,6 +31,14 @@ jobs:
       - name: Run unit tests
         run: flutter test --no-color
 
+      - name: Restore Android debug keystore
+        env:
+          ANDROID_DEBUG_KEYSTORE_BASE64: ${{ secrets.ANDROID_DEBUG_KEYSTORE_BASE64 }}
+        run: |
+          if [ -z "$ANDROID_DEBUG_KEYSTORE_BASE64" ]; then echo "ANDROID_DEBUG_KEYSTORE_BASE64 is not set. Aborting." && exit 1; fi
+          mkdir -p ~/.android
+          echo "$ANDROID_DEBUG_KEYSTORE_BASE64" | base64 --decode > ~/.android/debug.keystore
+
       - name: Build APK
         run: flutter build apk --release
 
