Testando credenciais

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,10 +2,6 @@ name: Main CI - Test, Build & Deploy
 on:
   push:
     branches: [ main ]
-    
-env:
-  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
-  FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
 
 jobs:
   android:
@@ -14,37 +10,47 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Set up Flutter
-        uses: subosito/flutter-action@v2
-        with:
-          flutter-version: '3.44.0'
+      # - name: Set up Flutter
+      #   uses: subosito/flutter-action@v2
+      #   with:
+      #     flutter-version: '3.44.0'
 
-      - name: Cache Pub
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/.pub-cache
-          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
-          restore-keys: |
-            ${{ runner.os }}-pub-
+      # - name: Cache Pub
+      #   uses: actions/cache@v4
+      #   with:
+      #     path: |
+      #       ~/.pub-cache
+      #     key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
+      #     restore-keys: |
+      #       ${{ runner.os }}-pub-
 
-      - name: Install dependencies
-        run: flutter pub get
+      # - name: Install dependencies
+      #   run: flutter pub get
 
-      - name: Run unit tests
-        run: flutter test --no-color
+      # - name: Run unit tests
+      #   run: flutter test --no-color
 
-      - name: Build App Bundle (AAB)
-        run: flutter build appbundle --release
+      # - name: Build App Bundle (AAB)
+      #   run: flutter build appbundle --release
 
-      - name: Install firebase-tools
-        run: npm install -g firebase-tools
+      # - name: Install firebase-tools
+      #   run: npm install -g firebase-tools
 
-      - name: Distribute to Firebase App Distribution
+      - name: Teste de credenciais de distribuição
+        env:
+          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
+          FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
         run: |
-          if [ -z "$FIREBASE_TOKEN" ]; then echo "FIREBASE_TOKEN is not set. Aborting." && exit 1; fi
-          if [ -z "$FIREBASE_ANDROID_APP_ID" ]; then echo "FIREBASE_ANDROID_APP_ID is not set. Aborting." && exit 1; fi
-          firebase appdistribution:distribute build/app/outputs/bundle/release/app-release.aab --app $FIREBASE_ANDROID_APP_ID --groups "UFBA - MATC89" --token "$FIREBASE_TOKEN"
+          echo "FIREBASE_TOKEN: ${FIREBASE_TOKEN}"
+          echo "FIREBASE_ANDROID_APP_ID: ${FIREBASE_ANDROID_APP_ID}"
+      # - name: Distribute to Firebase App Distribution
+      #   env:
+      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
+      #     FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
+      #   run: |
+      #     if [ -z "$FIREBASE_TOKEN" ]; then echo "FIREBASE_TOKEN is not set. Aborting." && exit 1; fi
+      #     if [ -z "$FIREBASE_ANDROID_APP_ID" ]; then echo "FIREBASE_ANDROID_APP_ID is not set. Aborting." && exit 1; fi
+      #     firebase appdistribution:distribute build/app/outputs/bundle/release/app-release.aab --app $FIREBASE_ANDROID_APP_ID --groups "UFBA - MATC89" --token "$FIREBASE_TOKEN"
 
   # ios:
   #   name: iOS: Test, Build IPA & Distribute
